# Use Node.js base image
FROM node:18

# Set working directory
WORKDIR /app

# Copy everything from root to container
COPY . .

# Move into the actual code directory
WORKDIR /app/app

# Install dependencies
RUN npm install

# Expose your service port (optional but good practice)
EXPOSE 5002

# Start the application
CMD ["node", "src/index.js"]
