FROM node:18

# Set working directory inside container
WORKDIR /app

# Copy user-service files
COPY services/user-service/app ./app

# Copy shared packages folder
COPY packages ./packages

# Go into the app working directory
WORKDIR /app/app

# Install dependencies
RUN npm install

# Expose the port (adjust as needed)
EXPOSE 5001

# Start the server
CMD ["node", "src/index.js"]
