FROM node:18-alpine

WORKDIR /app

# Copy environment files from root
COPY .env.development .env.development
COPY .env.production .env.production
COPY .env.uat .env.uat

# Copy only needed parts of the repo
COPY package package
COPY user-service/src src
COPY user-service/package.json package.json

# Install dependencies in production mode
RUN npm install --production

EXPOSE 3000
CMD ["node", "src/index.js"]