FROM node:18-alpine

WORKDIR /app

# Copy service code
COPY . .

# Copy environment files from root (assuming build context is set to the monorepo root)
COPY ../../.env.development .env.development
COPY ../../.env.production .env.production
COPY ../../.env.uat .env.uat

RUN npm install

CMD ["npx", "nodemon", "src/index.js"]

#techdev@toprise.in

#1235